// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD3Pv206v8stU0H8DuOV666OAdvq4voTtM',
    appId: '1:893324163599:web:6ed89a6f440f640b6d817a',
    messagingSenderId: '893324163599',
    projectId: 'ccom4401-1eecd',
    authDomain: 'ccom4401-1eecd.firebaseapp.com',
    storageBucket: 'ccom4401-1eecd.appspot.com',
    measurementId: 'G-XP2GD3JGQE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDhWhof3852rbWzCInCumHife2x81TBnbo',
    appId: '1:893324163599:android:7dce044456605a666d817a',
    messagingSenderId: '893324163599',
    projectId: 'ccom4401-1eecd',
    storageBucket: 'ccom4401-1eecd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAtCXLxRXwngcToELKMNasq1SCFme5TXag',
    appId: '1:893324163599:ios:91197e84a455a1fd6d817a',
    messagingSenderId: '893324163599',
    projectId: 'ccom4401-1eecd',
    storageBucket: 'ccom4401-1eecd.appspot.com',
    iosClientId:
        '893324163599-fuc3o68p972tlers0estb34l341u8ef7.apps.googleusercontent.com',
    iosBundleId: 'com.example.dataManagement',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAtCXLxRXwngcToELKMNasq1SCFme5TXag',
    appId: '1:893324163599:ios:91197e84a455a1fd6d817a',
    messagingSenderId: '893324163599',
    projectId: 'ccom4401-1eecd',
    storageBucket: 'ccom4401-1eecd.appspot.com',
    iosClientId:
        '893324163599-fuc3o68p972tlers0estb34l341u8ef7.apps.googleusercontent.com',
    iosBundleId: 'com.example.dataManagement',
  );
}
